### ISSUE TITLE
bug: operator < issue

### ISSUE THREAD

**Issue by mredstone6** [crashoz/uuid_v4#2]
# Bug description
The less or equal operator (and therefore the other operator) doesn't work. Indeed they don't have the anti-symmetric property. So we could have for instance 2 of ```UUID``` namely ```u1, u2``` such that ```u1 > u2``` and ```u2 > u1``` which break the logic for instance if we are planning to create a map of ```UUID```

# Fix
Replace the code line 163 of the file ```uuid_v4.h``` by:
```cpp
friend bool operator<(const UUID &lhs, const UUID &rhs) {
      // There are no trivial 128-bits comparisons in SSE/AVX
      // It's faster to compare two uint64_t
      uint64_t *x = (uint64_t*)lhs.data;
      uint64_t *y = (uint64_t*)rhs.data;
      return *x < *y || (*x == *y && *(x + 1) < *(y + 1));
}
```
> Note: We are defining here the first part of the 128-bits value to be the most significant value

**Comment by crashoz** [comment]
You are absolutely right, thank you for the bug report and fix!
